### ISSUE TITLE
buyLimit not working

### ISSUE THREAD

**Issue by cernicc** [abhinavk99/livecoin-api#3]
buyLimit api call is not working for me. I'm constantly getting a response:
```json
{ success: false, added: false, orderId: null, exception: null }
```

I've tried everything.

What additional data can I provide, so we can debug this issue?

**Comment by cernicc** [comment]
The thing is that authentication is working because I've tried getting balance and it worked.
I think that maybe signing the data or data for the order is the problem.

**Comment by abhinavk99** [comment]
I know you closed this, but I was wondering if you ever figured out what the problem was.
