### ISSUE TITLE
Example file?

### ISSUE THREAD

**Issue by agoralive** [abhinavk99/livecoin-api#5]
Hi

Would it be possible to create an example file where you include authorization, and create a trade between two markets?

I do not have much coding experience, but would like to play with this a bit :)

**Comment by abhinavk99** [comment]
I'm not sure what you mean by create a trade between two markets, but I can create an example file with buying and selling cryptocurrencies, if that works.

**Comment by abhinavk99** [comment]
I just made an example file, look over it and see if it's what you were looking for.

**Comment by abhinavk99** [comment]
Closed since no further response.
